FROM ubuntu:18.04
WORKDIR /tmp
COPY install_deps.sh ./
COPY ./urls.conf ./
# TODO
RUN chmod 777 /tmp
# 系统包 + Pip3.9
RUN cp -a /etc/apt/sources.list /etc/apt/sources.list.bak && \
    sed -i "s@http://.*archive.ubuntu.com@http://mirrors.huaweicloud.com@g" /etc/apt/sources.list && \
    sed -i "s@http://.*security.ubuntu.com@http://mirrors.huaweicloud.com@g" /etc/apt/sources.list
RUN apt update && \
    apt install --no-install-recommends ca-certificates -y && \
    apt install --no-install-recommends wget vim dos2unix net-tools ssh lsof sshpass -y && \
    apt install --no-install-recommends curl gcc g++ make pkg-config unzip autoconf autoconf -y && \
    apt install --no-install-recommends libblas3 liblapack3 gfortran libxml2 -y && \
    apt install --no-install-recommends pciutils liblapack-dev libblas-dev libffi-dev libssl-dev -y && \
    apt install --no-install-recommends zlib1g-dev xz-utils libgmpxx4ldbl -y && \
    apt clean && rm -rf /var/lib/apt/lists/*
# 安装Python
RUN . ./urls.conf && wget $PYTHON_DOCKR && \
    tar -xf Python-3.9.11.tar.xz && \
    cd Python-3.9.11 && \
    mkdir build && cd build && \
    ../configure --enable-shared --prefix=/usr/local/python3.9.11 && \
    make -j && make install && \
    cd .. && rm -rf build && cd .. && rm -rf Python-3.9.11 && rm -f Python-3.9.11.tar.xz && \
    ldconfig
ENV PATH=$PATH:/usr/local/python3.9.11/bin \
    LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/python3.9.11/lib
RUN mkdir ~/.pip && touch ~/.pip/pip.conf && \
    echo "[global]" > ~/.pip/pip.conf && \
    echo "trusted-host=mirrors.aliyun.com" >> ~/.pip/pip.conf && \
    echo "index-url=http://mirrors.aliyun.com/pypi/simple" >> ~/.pip/pip.conf && \
    echo "timeout=200" >> ~/.pip/pip.conf
# python包
RUN pip3.9 install -U pip && \
    pip3.9 install numpy && \
    pip3.9 install decorator && \
    pip3.9 install sympy==1.4 && \
    pip3.9 install cffi==1.12.3 && \
    pip3.9 install pyyaml && \
    pip3.9 install pathlib2 && \
    pip3.9 install protobuf && \
    pip3.9 install scipy && \
    pip3.9 install requests && \
    pip3.9 install attrs && \
    pip3.9 install psutil && \
    rm -rf /root/.cache/pip

# 安装cmake
RUN . ./urls.conf && wget $CMAKE_DOCKR && \
    tar xf cmake-3.23.1.tar.gz && cd cmake-3.23.1 && ./configure --prefix=/usr && \
    make -j && make -j install && cd .. && rm -rf cmake-3.23.1* && bash install_deps.sh
# 清理临时目录
RUN rm -rf ./*
